version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: mysql-mial
    restart: always
    environment:
      MYSQL_DATABASE: ln_mial
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mial_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ln_mial?serverTimezone=America/Lima&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - backend
    volumes:
      - images_data:/app/images

volumes:
  mysql_data:
  images_data:

networks:
  backend:
    name: mial_net